apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: helm-project

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.port }}

        envFrom:
        - secretRef:
            name: {{ .Values.existingSecret }}