name: Build and Deploy Backend

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR for Helm
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy with Helm
        run: |
          helm upgrade --install backend \
            oci://ghcr.io/zeinagab/internship-backend-chart/backend-chart \
            
            --namespace helm-project \
            --create-namespace \
            -f helm-values/values.yaml \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/backend \
            --set image.tag=${{ github.sha }}